[package]
name = "rust_pass_cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
md5 = "0.7"
sha2 = "0.10"
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
